"""
Sandbox service module for executing and testing code in a controlled environment.
---
Author: Ehiane Oigiagbe
Last Modified: November 5, 2025
"""

import re
import tempfile, os, subprocess, textwrap
from typing import List
from app.models.test_models import RunTestsRequest, RunTestsResponse, TestResult
from app.utils.errors import SandboxError
from app.utils.config import Config

SANDBOX_TIMEOUT_SEC = Config.SANDBOX_TIMEOUT_SECONDS

PYTEST_HEADER = textwrap.dedent("""
# auto-generated by Test4Case
""").strip()


def _extract_counts(text: str) -> dict:
    """
    Parse pytest's summary line(s), e.g.:
        "1 passed in 0.05s"
        "2 passed, 1 failed in 0.12s"
        "1 failed, 1 error in 0.10s"
        "1 passed, 2 skipped in 0.02s"
    Works with -q or default verbosity.
    """
    def pick(pat: str) -> int:
        m = re.search(pat, text, flags=re.IGNORECASE)
        return int(m.group(1)) if m else 0

    return {
        "passed":  pick(r"(\d+)\s+passed"),
        "failed":  pick(r"(\d+)\s+failed"),
        "errors":  pick(r"(\d+)\s+error[s]?"),
        "skipped": pick(r"(\d+)\s+skipped"),
    }


def run_pytest(req: RunTestsRequest) -> RunTestsResponse:
    """
    Run pytest tests in a sandboxed environment.
    """
    timeout = min(req.timeout_sec, SANDBOX_TIMEOUT_SEC)

    with tempfile.TemporaryDirectory() as tmp:
        user_path = os.path.join(tmp, "user_code.py")
        tests_path = os.path.join(tmp, "test_user_code.py")

        # Write user code and tests
        with open(user_path, "w", encoding="utf-8") as cf:
            cf.write(req.code)

        with open(tests_path, "w", encoding="utf-8") as tf:
            auto_import = "from user_code import *\n\n"
            tf.write(f"{PYTEST_HEADER}\n\n{auto_import}{req.tests_code}\n")

        # Pytest command
        # -q keeps output concise; our regex parser handles the summary line.
        cmd = ["python", "-m", "pytest", "-q", "--maxfail=1", tmp]

        try:
            proc = subprocess.run(
                cmd,
                cwd=tmp,
                capture_output=True,
                text=True,
                timeout=timeout
            )
        except subprocess.TimeoutExpired as e:
            raise SandboxError(f"Test execution timed out after {timeout} seconds.") from e

        raw = (proc.stdout or "") + (proc.stderr or "")

        # Robust parsing of summary counts
        counts = _extract_counts(raw)
        passed  = counts["passed"]
        failed  = counts["failed"]
        errors  = counts["errors"]
        skipped = counts["skipped"]

        # Aggregate result for MVP
        all_good = (failed == 0 and errors == 0)
        results: List[TestResult] = [
            TestResult(
                name="aggregate",
                status="passed" if all_good else "failed",
                message="All tests passed." if all_good else raw
            )
        ]

        return RunTestsResponse(
            passed=passed,
            failed=failed,
            errors=errors,
            skipped=skipped,
            results=results,
            raw_output=raw
        )
